# Generated by Django 5.0 on 2023-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
