# Generated by Django 5.0 on 2024-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_alter_profile_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
