# Generated by Django 5.0 on 2024-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
