# Generated by Django 5.0 on 2024-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='user-media/default-profile.jpg', upload_to='user-media/'),
        ),
    ]
